'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Stnc_Tweaker_5._0.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _138() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("138", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _231() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("231", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _276() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("276", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property about() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("about", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ara() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ara", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property baslat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("baslat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property baslık() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("baslık", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bil() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bil", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bil1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bil1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calistir() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calistir", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calistir1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calistir1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property denetim_masa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("denetim_masa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property donanim() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("donanim", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property donanim1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("donanim1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gecmiss() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gecmiss", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property internet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("internet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LaST__Cobalt__Control_Panel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LaST (Cobalt) Control Panel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LaST__Cobalt__Customize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LaST (Cobalt) Customize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property masaustuu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("masaustuu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property msimn_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("msimn_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property muzik() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("muzik", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property network__7_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("network (7)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property onay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("onay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property oturum() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("oturum", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pan_setting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pan setting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property personal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("personal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property prgekle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("prgekle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property res() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("res", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property resim() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("resim", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sd__143_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sd (143)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shell32_1001() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shell32_1001", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shell32_151() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shell32_151", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shell32_156() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shell32_156", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shell32_168() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shell32_168", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shell32_174() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shell32_174", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shell32_20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shell32_20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shell32_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shell32_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shell32_41() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shell32_41", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shell32_54() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shell32_54", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WMP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WMP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
